export const TOGGLE_MENU = "TOGGLE_MENU";
export const TOGGLE_MESSAGE = "TOGGLE_MESSAGE";
export const TOGGLE_NOTIFICATION = "TOGGLE_NOTIFICATION";
export const TOGGLE_PROFILE = "TOGGLE_PROFILE";
export const CLOSE_POP_UP = "CLOSE_POP_UP";
